### ISSUE TITLE
Experiments -- TODO

### ISSUE THREAD

**Issue by huangyihe** [nathanielherman/sto#13]
* [x] Document detailed experiment info like date/time, STO version used, and parameters
* [ ] Investigate the performance difference between boosting and STO in `vacation`
 * e.g. run time breakdown, abort rate, etc.
* [x] Take a look at `TGeneric`
* [x] More info on the "11%" number
 * without the full opacity check, vacation high contention at 16 threads takes 37.79 seconds to finish, compared to 32.37 seconds (a **14.34%** improvement) with `hard_check_opacity()`
 * abort rate also went down from 21.65% to 16.26% (1869436 hco aborts out of a total of 3055493 hco calls, or 61.2%)
